---
  name: Nightly check
  
  on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch: {}
  
  concurrency:
    group: nightly-${{ github.ref }}
    cancel-in-progress: true
  
  jobs:
    linkCheckMdx:
      name: Run link check on .mdx files
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: LinkCheck mdx files
          uses: ConsenSys/docs-gha/linkcheck@main
          with:
              FILE_EXTENSION: mdx
              MODIFIED_FILES_ONLY: no
    linkCheckMd:
      needs: linkCheckMdx
      name: Run link check on .md files
      if: always()
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: LinkCheck md files
          uses: ConsenSys/docs-gha/linkcheck@main
          with:
              FILE_EXTENSION: md
              MODIFIED_FILES_ONLY: no

    slackNotification:
      needs: [linkCheckMdx, linkCheckMd]
      if: ${{ failure() }}
      runs-on: ubuntu-latest
      steps:
        - name: Slack Notification
          uses: slackapi/slack-github-action@2a8087d4af6f83146a87539a70defe909fe6dbe6
          with:
            payload: |
              {
                "channel": "#doc-ci-alerts",
                "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} workflow failed> on ${{ github.ref }} branch in the ${{ github.repository }} repository!"
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}